print(dir(tuple))
seq = (2,8,23,97,92,44,17,39,11,12)
help(seq.index)
help(seq.count)
print(seq.count(8))
print(seq.index(44))
listseq = list(seq)
print(type(listseq))
print(len(seq))
print(min(seq))
print(max(seq))